<h5>Import dataset</h5>
<h6>Load the dataset from a file .csv<br>
Font: https://www.footballwebpages.co.uk/premier-league/league-table<h6>

In [2]:
import numpy as np
import pandas as pd

pd.set_option('display.min_rows', 200)
pd.set_option("display.max_rows", 600)
pd.set_option("display.max_columns", 100)

df = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/E0.csv")

df.rename(columns={"Date":"date", "Time":"time", "FTHG":"full_time_home_goals", "FTAG":"full_time_away_goals", "FTR":"full_time_result", 
                   "HomeTeam":"home_team", "AwayTeam":"away_team", "HTHG":"half_time_home_team_goals", 
                   "HTAG":"half_time_away_team_goals", "HTR":"half_time_result", "HS":"home_team_shots", "AS":"away_team_shots", 
                   "HST":"home_team_shots_on_target", "AST":"away_team_shots_on_target"}, inplace=True)
df = df.astype({"date":"datetime64"})
df = df.convert_dtypes(infer_objects=True)
#df = df[["date", "home_team", "away_team", "full_time_home_goals", "full_time_away_goals", "full_time_result", "B365H", "B365D", "B365A", "PSH", "PSD", "PSA"]]
df.tail()

,Div,date,time,home_team,away_team,full_time_home_goals,full_time_away_goals,full_time_result,half_time_home_team_goals,half_time_away_team_goals,half_time_result,Referee,home_team_shots,away_team_shots,home_team_shots_on_target,away_team_shots_on_target,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,B365>2.5,B365<2.5,...,AHh,B365AHH,B365AHA,PAHH,PAHA,MaxAHH,MaxAHA,AvgAHH,AvgAHA,B365CH,B365CD,B365CA,BWCH,BWCD,BWCA,IWCH,IWCD,IWCA,PSCH,PSCD,PSCA,WHCH,WHCD,WHCA,VCCH,VCCD,VCCA,MaxCH,MaxCD,MaxCA,AvgCH,AvgCD,AvgCA,B365C>2.5,B365C<2.5,PC>2.5,PC<2.5,MaxC>2.5,MaxC<2.5,AvgC>2.5,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
226,E0,2023-02-18,15:00,Nott'm Forest,Man City,1,1,D,0,1,A,G Scott,4,26,1,6,8,6,0,10,1,0,0,0,8.50,5.50,1.30,10.00,5.5,1.30,9.50,5.75,1.3,10.30,5.67,1.33,10.00,5.5,1.29,10.50,5.25,1.25,11.00,5.90,1.34,10.01,5.62,1.31,1.62,2.30,...,1.50,1.99,1.91,2.00,1.93,2.02,1.94,1.97,1.90,10.00,5.5,1.29,11.50,5.5,1.26,9.50,4.8,1.35,10.50,5.40,1.33,11.00,5.50,1.27,11.50,5.50,1.22,13.00,6.20,1.35,10.83,5.46,1.31,1.62,2.30,1.61,2.44,1.70,2.47,1.61,2.35,1.75,1.85,2.05,1.93,2.00,1.93,2.10,1.85,2.03
227,E0,2023-02-18,15:00,Wolves,Bournemouth,0,1,A,0,0,D,M Salisbury,15,5,4,1,12,10,12,2,3,3,0,0,1.67,3.60,6.00,1.65,3.8,5.25,1.67,3.75,5.5,1.69,3.86,5.78,1.67,3.7,5.25,1.62,3.50,5.50,1.72,3.95,6.10,1.68,3.81,5.53,2.10,1.73,...,-0.75,1.88,2.02,1.89,2.04,1.92,2.06,1.87,2.00,1.75,3.6,4.75,1.83,3.5,4.40,1.80,3.6,4.50,1.83,3.62,4.98,1.78,3.50,4.75,1.75,3.40,4.60,1.86,3.70,5.00,1.82,3.60,4.71,2.08,1.82,2.03,1.88,2.13,1.90,2.04,1.82,-0.50,1.77,2.02,1.82,2.11,1.86,2.14,1.82,2.07
228,E0,2023-02-18,17:30,Newcastle,Liverpool,0,2,A,0,2,A,A Taylor,14,13,4,7,3,8,6,7,1,1,1,0,2.50,3.50,2.70,2.45,3.5,2.75,2.50,3.45,2.7,2.57,3.58,2.82,2.50,3.4,2.70,2.50,3.30,2.63,2.70,3.65,2.83,2.57,3.51,2.75,1.80,2.00,...,0.00,1.88,2.02,1.87,2.06,1.95,2.08,1.88,2.01,2.45,3.4,2.80,2.45,3.4,2.75,2.50,3.4,2.75,2.56,3.52,2.88,2.45,3.30,2.88,2.45,3.25,2.70,2.74,3.58,2.95,2.53,3.48,2.82,1.88,2.02,1.88,2.02,1.94,2.13,1.85,2.00,0.00,1.82,2.08,1.85,2.09,1.91,2.12,1.83,2.07
229,E0,2023-02-19,14:00,Man United,Leicester,3,0,H,1,0,H,S Attwell,26,19,8,3,9,9,6,6,0,2,0,0,1.62,4.33,5.25,1.60,4.2,5.25,1.60,4.30,5.0,1.65,4.34,5.37,1.60,4.2,5.00,1.57,4.00,5.00,1.66,4.50,5.50,1.62,4.32,5.22,1.62,2.30,...,-1.00,2.02,1.77,2.08,1.85,2.10,1.89,2.04,1.84,1.55,4.5,5.75,1.53,4.4,5.50,1.55,4.5,5.50,1.58,4.53,5.87,1.55,4.33,5.50,1.50,4.20,5.50,1.62,4.70,6.10,1.56,4.49,5.70,1.57,2.38,1.63,2.42,1.63,2.58,1.58,2.43,-1.00,1.91,1.99,1.93,2.00,1.95,2.04,1.90,1.97
230,E0,2023-02-19,16:30,Tottenham,West Ham,2,0,H,0,0,D,M Oliver,16,6,6,1,16,10,4,7,2,1,0,0,1.75,3.60,4.75,1.77,3.7,4.50,1.80,3.70,4.3,1.87,3.76,4.47,1.83,3.6,4.20,1.75,3.50,4.33,1.88,3.86,4.75,1.83,3.76,4.39,1.88,2.02,...,-0.50,1.77,2.02,1.87,2.06,1.87,2.12,1.82,2.05,1.83,3.4,4.50,1.85,3.5,4.33,1.90,3.4,4.50,1.88,3.53,4.72,1.83,3.50,4.33,1.80,3.40,4.33,1.92,3.70,5.09,1.87,3.51,4.50,2.10,1.73,2.14,1.78,2.16,1.86,2.06,1.78,-0.50,1.88,2.02,1.88,2.04,1.93,2.06,1.88,2.00

<h5>Mean odds home/draw/away per Team - BET365</h5>

In [3]:
odds_home_team_mean = df.groupby(df["home_team"])["B365H"].mean()
odds_draw_team_mean = df.groupby(df["home_team"])["B365D"].mean()
odds_away_team_mean = df.groupby(df["away_team"])["B365A"].mean()

odds_mean = pd.concat([odds_home_team_mean, odds_draw_team_mean, odds_away_team_mean], axis=1)
odds_mean

                   B365H     B365D      B365A
Arsenal         1.770000  4.464545   1.860000
Aston Villa     3.249167  3.779167   4.168182
Bournemouth     4.056364  3.554545  10.150000
Brentford       3.077500  3.660833   4.816364
Brighton        2.271818  3.804545   4.090909
Chelsea         2.012727  4.231818   2.135000
Crystal Palace  3.108333  3.479167   5.965455
Everton         3.737500  3.616667   5.754545
Fulham          3.410833  3.712500   6.043333
Leeds           3.681818  3.927273   4.445833
Leicester       3.270909  3.927273   4.790000
Liverpool       1.557273  5.711818   1.829091
Man City        1.177500  8.520833   1.560000
Man United      2.221667  4.334167   2.726667
Newcastle       2.269167  3.965000   3.261818
Nott'm Forest   4.573333  3.891667   8.041818
Southampton     3.439091  3.577273   6.135000
Tottenham       2.085833  4.204167   2.800000
West Ham        2.742727  3.722727   4.141667
Wolves          3.520833  3.650000   4.772727

<h5>Mean goals home/away per Team</h5>

In [4]:
goals_home_team_mean = df.groupby(df["home_team"])["full_time_home_goals"].mean()
goals_away_team_mean = df.groupby(df["away_team"])["full_time_away_goals"].mean()
goals_team_mean = (goals_home_team_mean + goals_away_team_mean) / 2

goals_mean = pd.concat([goals_home_team_mean, goals_away_team_mean, goals_team_mean], axis=1, keys = ['goals_home_team_mean', 'goals_away_team_mean', 'goals_team_mean']).round(3)
goals_mean

                goals_home_team_mean  goals_away_team_mean  goals_team_mean
Arsenal                        2.455                 2.000            2.227
Aston Villa                    1.583                 0.818            1.201
Bournemouth                    1.000                 0.833            0.917
Brentford                      2.000                 1.182            1.591
Brighton                       1.545                 2.000            1.773
Chelsea                        1.182                 0.833            1.008
Crystal Palace                 1.000                 0.818            0.909
Everton                        0.917                 0.545            0.731
Fulham                         1.667                 1.250            1.458
Leeds                          1.364                 1.083            1.223
Leicester                      1.364                 1.750            1.557
Liverpool                      2.273                 1.182            1.727
Man City                       3.417                 1.583            2.500
Man United                     2.000                 1.417            1.708
Newcastle                      1.583                 1.455            1.519
Nott'm Forest                  1.250                 0.273            0.761
Southampton                    0.909                 0.750            0.830
Tottenham                      2.000                 1.667            1.833
West Ham                       1.091                 0.583            0.837
Wolves                         0.750                 0.727            0.739

In [5]:
def season_results(team):
    # Filter
    home_team = df.loc[df["home_team"] == team]
    away_team = df.loc[df["away_team"] == team]

    # Goals scored sum
    home_team_goals_scored_sum = home_team["full_time_home_goals"].sum()
    away_team_goals_scored_sum = away_team["full_time_away_goals"].sum()
    goals_scored = home_team_goals_scored_sum + away_team_goals_scored_sum

    # Goals conceded sum
    home_team_goals_conceded_sum = home_team["full_time_away_goals"].sum()
    away_team_goals_conceded_sum = away_team["full_time_home_goals"].sum()
    goals_conceded = home_team_goals_conceded_sum + away_team_goals_conceded_sum

    # Goals scored mean
    home_team_goals_scored_mean = home_team["full_time_home_goals"].mean()
    away_team_goals_scored_mean = away_team["full_time_away_goals"].mean()

    # Goals conceded mean
    home_team_goals_conceded_mean = home_team["full_time_away_goals"].mean()
    away_team_goals_conceded_mean = away_team["full_time_home_goals"].mean()

    print(f"The {team} have scored a total of {goals_scored} goals in this season.")
    print(f"The {team} have conceded score a total of {goals_conceded} goals in this season.")
    print(f"The {team} have scored a total of {home_team_goals_scored_sum} goals in this home.")
    print(f"The {team} have scored a total of {away_team_goals_scored_sum} away goals.")
    print(f"The {team} have conceded score a total of {home_team_goals_conceded_sum} goals in this home.")
    print(f"The {team} have conceded score a total of {away_team_goals_conceded_sum} away goals.")
    print(f"The {team} have a mean of score {home_team_goals_scored_mean.round(2)} goals in this home.")
    print(f"The {team} have a mean of score {away_team_goals_scored_mean.round(2)} away goals.")
    print(f"The {team} have a mean of conceded score of {home_team_goals_conceded_mean.round(2)} goals in this home.")
    print(f"The {team} have a mean of conceded score of {away_team_goals_conceded_mean.round(2)} away goals.")

team = "Aston Villa"
season_results(team)

The Aston Villa have scored a total of 28 goals in this season.
The Aston Villa have conceded score a total of 38 goals in this season.
The Aston Villa have scored a total of 19 goals in this home.
The Aston Villa have scored a total of 9 away goals.
The Aston Villa have conceded score a total of 19 goals in this home.
The Aston Villa have conceded score a total of 19 away goals.
The Aston Villa have a mean of score 1.58 goals in this home.
The Aston Villa have a mean of score 0.82 away goals.
The Aston Villa have a mean of conceded score of 1.58 goals in this home.
The Aston Villa have a mean of conceded score of 1.73 away goals.

In [6]:
# Filter
home_team = df.loc[df["home_team"] == "Aston Villa"]
away_team = df.loc[df["away_team"] == "Aston Villa"]

# Goals scored mean
home_team_goals_scored_mean = home_team["full_time_home_goals"].mean()
away_team_goals_scored_sum = away_team["full_time_away_goals"].sum()
goals_scored = home_team_goals_scored_mean + away_team_goals_scored_sum

# Goals conceded
home_team_goals_conceded_sum = home_team["full_time_away_goals"].sum()
away_team_goals_conceded_sum = away_team["full_time_home_goals"].sum()
goals_conceded = home_team_goals_conceded_sum + away_team_goals_conceded_sum

home_team_goals_scored_mean

1.5833333333333333